### ISSUE TITLE
Code Quality

### ISSUE THREAD

**Issue by NeelzDev** [darenegade/BikeBattle#10]
Wollen wir für die Code Qualität und Analyse einheitliche Style Checker wie Checkstyle, Findbugs, pmd und simian benutzen?
Damit würden wir sicherstellen, dass unsere Code auch das gleiche Format hat.
Wir könnten die aus Software Architektur verwenden.

**Comment by darenegade** [comment]
Definitiv!

Als Alternative zu der Config vom Schiedi können wir auch die von Google hernehmen:
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml

**Comment by NeelzDev** [comment]
Ja das macht Sinn die von Google zu nehmen.

Sollen wir darüber hinaus auch noch andere einsetzen?
Das Aufzeigen von redundanten Code bei simian (wenn ich mich nicht irre) fand ich persönlich auch ganz praktisch.

**Comment by darenegade** [comment]
Also ich nutze IntelliJ, auf dem Android Studio basiert, und das seit Anfang des Jahres auch Duplicate feststellt und zeigt dir diese direkt in der IDE indem es den Code gelb unterkringelt. 
Da Android Studio darauf basiert, sollte es die aktuelle Version auch können. Kannst ja mal ausprobieren.

**Comment by NeelzDev** [comment]
Hab dieses Jahr noch nicht mit Android Studio gearbeitet. 
Ich kuck es mir mal an wäre ja sehr praktisch.

**Comment by NeelzDev** [comment]
Also Android Studio benutzt lint (http://developer.android.com/tools/debugging/improving-w-lint.html) für die Code Analyse. Denke zusammen mit Checkstyle sind wir da gut aufgestellt.

FYI: Um den Code zu analysieren einfach aufs Projekt gehen und dann unter analyse -> inspect code benutzen.
Für checkstyle kann ein Plugin genutzt werden oder man benutzt es extern.

**Comment by NeelzDev** [comment]
Hab jetzt mal mit dem Checkstyle Plugin https://plugins.jetbrains.com/plugin/1065 und den oben genannten Regeln angefangen meinen Code zu korrigieren. Allerdings beschwert sich das ganze immer über die Einrücktiefe, obwohl diese ja ohnehin automatisch eingestellt ist, und man das ja erst manuell ändern müsste.
Noch jemand diesen Fehler gehabt?

**Comment by darenegade** [comment]
Hast du kontrolliert, dass die Einrückung über 4 Leerzeichen eingestellt ist? Standard ist glaub ich Tab.

**Comment by NeelzDev** [comment]
Okay. Dachte der Standard würde den Guidelines entsprechen. Das wird das Problem sein. Danke

**Comment by NeelzDev** [comment]
Okay vllt doch was anderes. Die Einrücktiefe ist einfach doppelt so groß wie gedacht eingestellt gewesen.

Für die anderen falls ihr das auch einstellen müsst:
Unter Settings->Editor->Code Style->Java "Tab size" und "Indent" auf 2 Stellen und "Continuation indent" auf 4.
