### ISSUE TITLE
Überführung in HM .git und redmine

### ISSUE THREAD

**Issue by darenegade** [darenegade/BikeBattle#12]
Siehe https://redmine.pn.cs.hm.edu

**Comment by darenegade** [comment]
https://www.smashingmagazine.com/2014/05/moving-git-repository-new-server/

**Comment by NeelzDev** [comment]
Ggf. die Sachen neu erstellen, da ja sonst auch verloren geht, wer was bisher gemacht hat, oder kann man die Benutzer später neuen Usern zuordnen?

Also Rene könnte das Projekt mit Lombok aufsetzen und pushen und alle eröffnen ihre Branches neu und laden ihren Soure code hoch?

**Comment by NeelzDev** [comment]
Das wäre ja dann geklärt.
