### ISSUE TITLE
Projekt Steckbrief

### ISSUE THREAD

**Issue by darenegade** [darenegade/BikeBattle#13]
https://moodle.hm.edu/mod/resource/view.php?id=213708

**Comment by NeelzDev** [comment]
[Projektsteckbrief.pdf](https://github.com/darenegade/BikeBattle/files/195523/Projektsteckbrief.pdf)

**Comment by NeelzDev** [comment]
Alle mit dem Steckbrief einverstanden, damit ich den hochladen kann?

**Comment by Plebo13** [comment]
Von mir aus passt der.

**Comment by darenegade** [comment]
Man kann die Beschreibung der Funktionen noch ausweiten. Z.B. Sollen nicht nur Zeit vergleichbar sein, sondern auch Geschwindigkeit. Dann soll es Vergleiche in Routen und Allgemeine Vergleiche mit Freunden geben. Z.B. Wer fährt diese Woche am meisten. Oder Wer schafft den Top-Speed. Dann soll es noch Achievements geben.

**Comment by NeelzDev** [comment]
[Projektsteckbrief.pdf](https://github.com/darenegade/BikeBattle/files/202050/Projektsteckbrief.pdf)

besser?
