### ISSUE TITLE
Eintragen in Teammitglieder.md

### ISSUE THREAD

**Issue by darenegade** [darenegade/BikeBattle#17]
@munichsven @HoldemJhon @Plebo13 

Wenn alle drin sind, bitte Issue schließen.

**Comment by NeelzDev** [comment]
Sollte nicht der Nickname in der Tabelle auch enthalten sein?

**Comment by darenegade** [comment]
Du kannst die Tabelle gerne erweitern. Bei mir ist es egal, da ich den Commit nicht mit meinem Nicknamen durchführe sondern mit meinem richtigen Namen und meine private Mail. Deswegen braucht er nur das Mapping von meiner Privaten auf die HM Mail.
Github verknüpft über die im Commit angegebene Mail den Account und ersetzt das mit deinem Github Nick. D.h. nicht dass dein Nickname im Commit steht.
Musst mal schauen, wie du dein IntelliJ bzw. AndroidStudio eingestellt hast.
Mit folgenden Befehlen im Terminal kannst du deinen Commit Namen und Mail anschauen:

```
git config --global user.name
git config --global user.email
```

Wenn du es ändern willst, dann einfach den gleichen Befehl nehmen und deinen Namen mit Anführungsstrichen `"Name"` anfügen und ausführen.

**Comment by darenegade** [comment]
@munichsven Bitte noch eintragen!

**Comment by darenegade** [comment]
@munichsven Irgendwie bist du nicht drin. Bitte wieder eintragen!
