### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by NeelzDev** [darenegade/BikeBattle#21]
Ich habe mich dafür entschieden zwei Versionen des Trackers zu implementieren. Die Funktionen werden dann durch ein Interface definiert.
Einmal gibt es das ganze über die GoogleAPI und einmal über die Android Bibliothek. 
Letzteres wird wohl benutzt werden, aber, da ich das erste am Dienstag schon lauffähig hatte, dachte ich mir, dass man es behalten kann. Möglicherweise für einen Vergleich auch ganz interessant.

Denke da spricht nichts gegen oder? :)

**Comment by darenegade** [comment]
Wenn es eh schon da ist, dann können wir es auch behalten

**Comment by Plebo13** [comment]
Kann von mir aus drin bleiben. Wo genau liegt bei den beiden denn der Unterschied?

**Comment by NeelzDev** [comment]
Die GoogleApi ist eigentlich der neue Standard. Das Problem ist, dass hier nur alle 5 Sekunden etwa ein update kommt. Dies ist eigentlich zu wenig. (Bei 25 km/h wäre es weniger als ein Punkt alle 30m).
