### ISSUE TITLE
Ausgewählte Route an neue Activity übergeben

### ISSUE THREAD

**Issue by Plebo13** [darenegade/BikeBattle#22]
Ich sitze gerade an der Activity, die dem User alle Informationen zur ausgewählten Route anzeigt. Kriege es aber einfach nicht hin, die Route von der einen Activity zur anderen zu übergeben. Wenn ich
einfach nur die Routenklasse serializable mache und über den Intent übergebe, kriegt die neue Activity nur eine List<Location>, kann diese aber nicht mehr zurück zu Route casten. Informationen wie Length oder Name gehen also verloren.
Habe dann die aufrufende Activity serializable, gemacht und über Intent übergeben. Greife dann über diese Activity auf die Route zu. Funktioniert auch soweit, allerdings sind alle Attribute der Route, außer der Name, null.
Hat einer von euch da Erfahrung?

**Comment by NeelzDev** [comment]
Es sollte über serializable gehen, falls serializable korrekt implementiert ist. Das müsste ja dann im Modell gemacht werden.

**Comment by NeelzDev** [comment]
http://www.onjava.com/pub/a/onjava/excerpt/JavaRMI_10/?page=3

Das reine implementieren von serializable reicht nur dann aus, wenn jedes Feld serializable ist, was aber bei Route bzw. der LocationList nicht der Fall ist.

**Comment by darenegade** [comment]
Hast du mal Parcelable statt Serializable ausprobiert. Location ist Parcelable, daher sollte das die besser Wahl sein.

**Comment by darenegade** [comment]
Wir sollten uns aber generell mal über die Architektur Gedanken machen, da mit einer guten Architektur das übergeben von Daten aus dem Modell vielleicht überflüssig wird.

Gerade MVP ist unter Android wohl eine gute Wahl. Hierzu gibt es viele gute Artikel:
https://github.com/konmik/konmik.github.io/wiki/Introduction-to-Model-View-Presenter-on-Android
http://schlingel.bplaced.net/android_mit_mvp_strukturieren.html
https://medium.com/mobiwise-blog/android-basic-project-architecture-for-mvp-72f4b33252d0#.8d4qn0o9d

**Comment by NeelzDev** [comment]
Parcelable dürfte tatsächlich die bessere Variante sein.

Ich vermute mal,  wenn wir nicht alle Sachen in einer Activity laufen lassen, kommen wir um das übergeben von Daten nicht rum. Und alles in einer Activity finde ich eigentlich nicht so gut, da das ja dem Prinzip von Android widerspricht.

**Comment by darenegade** [comment]
Ich denke, dass Thema hat sich erst einmal erledigt
