### ISSUE TITLE
Zwischen-Präsentaitonen

### ISSUE THREAD

**Issue by NeelzDev** [darenegade/BikeBattle#31]
Hier mal der erste Entwurf des Gannt Diagramms. Der Rumpf unserer Präsentation liegt auch im git.
[BikeBattle.pdf](https://github.com/darenegade/BikeBattle/files/250522/BikeBattle.pdf)

**Comment by darenegade** [comment]
Folgende Punkte von mir zur Präsentation:
- Der Meilenstein Grundstruktur ist zu weit hinten. Im Steckbrief hatten wir 26.04. Dass hatten wir nicht geschafft. Also haben wir ihn nach hinten verlegt, aber 24.05 ist zu weit. Es steht ja schon fast alles. Ich würde 15.05 sagen.
- Da sich die Meilensteine verschoben haben, würde ich das Projekt auf Status gelb setzen.
- Auf der ersten Folie würde ich nicht den Login reinnehmen. Es wird nur eine vor Ort Demo geben mit Anmelden und dann Routen anzeigen. Auf der ersten Folie müssen wir etwas Werbung machen. Denkt an SE2. Wir müssen unsere App verkaufen. Habt ihr hier Ideen, wie man das am besten verkaufen kann?
- Live Demo und Video würde ich tauschen. Dann ist es logischer aufgebaut.
- Gantt Diagramm ist sehr gut
- Eine Folie zum Schluss noch mit Problemen und wie es weiter geht. Hierzu muss jeder etwas beitragen.

**Comment by darenegade** [comment]
**Probleme** 
- Schwierigkeiten mit der API, da es keine gute Bibliothek für HATEOAS mit Android gibt
- Probleme mit der 64k Dex Beschränkung -> Multi-Dex notwendig
- Allgemein Startschwierigkeiten -> Architektur festlegen, in falsche Richtungen laufen usw.

**Wie geht es weiter**
- Google OAuth2 Token Lifecycle implementieren
- Backend optimieren zur Entlastung der App
- Daten Caching in der App

**Comment by NeelzDev** [comment]
Zu den Meilensteine. Das sollen die zukünftigen sein. Da MongoDB schon steht habe ich es rausgenommen und stattdessen die Activity die @munichsven grade noch schreibt. 
Ja die Folien waren nur zur Übersicht was rein soll. Sind gelöscht. Nun gibt es nur die Übersicht zu Beginn dann kommt Dann zeigt Lukas offline den Login und das Routen suchen.
Danach wird in der Präsentation das Video gezeigt und von mir erläutert. 
Als nächste Folie kommt die, welche du Beschrieben hast mit Problemen und wie es weitergeht.
Zuletzt dann das Gant Diagramm. So will es auf jeden Fall seine Struktur.

**Comment by NeelzDev** [comment]
**Probleme**
- FusedAPI von Google gibt nur alle 5s einen Position --> AndroidAPI nutzen

**Wie es weiter geht**
- Routing testen und einbauen
- GUI verbesserungen
- Testen testen testen

**Comment by munichsven** [comment]
Probleme

```
dependencies Verwaltung
```

Wie es weiter geht

```
Profil mit echten Daten 
Profil Funktionen erweitern
GUI verbesserungen
```

   Testen

**Comment by Plebo13** [comment]
**Probleme**
- Serialization von eigenen Klassen (nicht mehr notwendig)

**Wie es weiter geht**
- RoutingActivity fertigstellen
- GUI verbesserungen
- Backend komplett einbinden
