### ISSUE TITLE
Fehler im Modell

### ISSUE THREAD

**Issue by Plebo13** [darenegade/BikeBattle#33]
Im Track in der calculateTime müssen die beiden Operanden in der Subtraktion vertauscht werden und die Einheit ist Millisekunden nicht Sekunden.
Soll ich das in meinem Branch ändern?

**Comment by Plebo13** [comment]
Habe es jetzt gelöst und ist dann mit dem GUI pull request im Master.

**Comment by NeelzDev** [comment]
Das mit der Zeit solltest du in der gui glaub ich anders lösen, da es bei längeren Zeitabständen sonst keinen kontinuierlichen Timer gibt, also am besten über die startzeit gehen und dann mittels currentime die Differenz bilden.

**Comment by NeelzDev** [comment]
die gettime ist mehr für die statistik am ende gedacht. Aber mit dem fehler stimmt natürlich trotzdem.
