### ISSUE TITLE
Routen finden

### ISSUE THREAD

**Issue by darenegade** [darenegade/BikeBattle#4]
Als User möchte ich Routen in der Nähe sehen

**Comment by Plebo13** [comment]
Die Standortbestimmung funktioniert jetzt.

Zu den Routen habe ich euch mal einen Screenshot via Slack geschickt. Funktioniert soweit ganz gut: Ich habe händisch eine Route mit vier Wegpunkten erstellt, der Route einen Namen gegeben und diese dann über die MapActivity anzeigen lassen.

**Comment by darenegade** [comment]
#57
