### ISSUE TITLE
Routen fahren

### ISSUE THREAD

**Issue by darenegade** [darenegade/BikeBattle#5]
Als User möchte ich vorhandene Routen abfahren können und meine Daten speichern können.

**Comment by NeelzDev** [comment]
Würde sagen wichtig beim Routenfahren ist der Vergleich, dass der Fahrer sich noch auf der Route befindet. Hierbei denke ich dass man mit einer gewissen Toleranz agieren muss, wie hoch diese ist müssen wir bei Tests noch herausfinden.

**Comment by darenegade** [comment]
#57
