### ISSUE TITLE
Route anzeigen

### ISSUE THREAD

**Issue by darenegade** [darenegade/BikeBattle#6]
Als User möchte ich mir Routen anschauen und die Zeiten anderer User sehen.

**Comment by NeelzDev** [comment]
Lukas erste Darstellung finde ich schon mal sehr schön.

Für spätere Meilensteine fände ich die Unterstützung von Opensource Formaten wie OpenStreet-/OpenCycleMap sehr interessant.

**Comment by Plebo13** [comment]
Da habe ich mich schonmal recht kurz mit befasst, ginge auch, ist nur etwas komplizierter, da OSM natürlich nicht so schön in Android eingebunden ist.
Ich kann aber nochmal angehen und auch jetzt schon direkt damit anfangen, dann spare ich mir doppelte Arbeit :P

**Comment by NeelzDev** [comment]
Ich würde erstmal nicht zu viel Arbeit in die Richtung investieren, es seidenn es läst sich wirklich kombinieren.
