### ISSUE TITLE
Schriftfarben anpassen

### ISSUE THREAD

**Issue by darenegade** [darenegade/BikeBattle#66]
Farben überall kontrollieren und anpassen.
Z.B. TrackingActivity Anzeige Daten

**Comment by Plebo13** [comment]
Kümmere ich mich drum

**Comment by Plebo13** [comment]
Welche Farben meinst du genau? Die TextViews stehen auf 'primary_text'

**Comment by darenegade** [comment]
Das heißt nicht, dass es gut aussieht. 😄

**Comment by darenegade** [comment]
Du kannst die Primary Text Farbe gerne ändern oder eine weitere hinzufügen, falls die Kombi nicht passt.

**Comment by darenegade** [comment]
Ich hab mal ein anderes Login Bild eingefügt und die primary + accent Farben an das Bild angepasst.

**Comment by Plebo13** [comment]
Farben finde ich sehr gut!

**Comment by darenegade** [comment]
Schaut FAST professionell aus, oder XD

**Comment by Plebo13** [comment]
Nicht nur fast :D
