### ISSUE TITLE
Datenmodell festlegen

### ISSUE THREAD

**Issue by darenegade** [darenegade/BikeBattle#7]
Das Datenmodell im Backende muss modelliert werden und kann hier diskutiert werden.

draw.io ist hier ziemlich cool.

**Comment by darenegade** [comment]
Erste Basis vom Datenmodell für die Diskussion.

![datamodel](https://cloud.githubusercontent.com/assets/10849776/13957954/96944b7c-f04e-11e5-87d2-8ca69c9b9a54.png)

**Comment by NeelzDev** [comment]
Also das Datenmodell gefällt mir ganz gut. Was ist mit privat bei Route gemeint? Quasi nur ein Flag, dass die Route nur für den User zur Verfügung steht?

Das Datenmodell beschreibt wie die Daten gespeichert werden sollen oder? Also darauf bezieht sich meine folgende Aussage:
Ich glaub der Wert Geschwindigkeit ist redundant, da sich das aus der Zeit und der Länge ergibt. Ich finde die Länge sollte zusätzlich bei Route gespeichert werden, da dies ja mitunter ein Auswahlkriterium für potenzielle Nutzer darstellt.

**Comment by darenegade** [comment]
Genau, privat soll eine Art Flag sein, um zu erkennen, ob die Route mit fremden Personen geteilt werden soll oder nur mit freigegebnen Freunden. Irgendwie so...
Das Datenmodell beschreibt die Datenhaltung im Backend.
Das Attribut Geschwindigkeit ist eher ein Platzhalter für ein komplexeres System, dass ich noch nicht beschreiben wollte. Mit der Zeit bekommst du ja nur die Durchschnittsgeschwindigkeit, aber du willst ja vielleicht eine genauer Grafik haben, wo man sieht welche Geschwindigkeit man zu welchen Zeitpunkt hatte und somit auch Höchstgeschwindigkeit usw.
Die Länge ist ein guter Punkt wo ich auch überlegt habe, da man diese ja auch Theoretisch aus den Abständen der Streckenpunkte berechnen kann. Aber man kann es auch noch mal sep. speichern.

**Comment by NeelzDev** [comment]
Okay ich hatte es direkt als Durchschnitt interpretiert.

Ich vermute mal, dass es das sinnvollste wäre, hier auch die einzelnen Streckenpunkte vom Tracking mit einem jeweiligen Zeitstempel zu speichern. Die Streckenpunkte weichen ja etwas von denen der vorgegebenen Route ab (Messungenauigkeiten etc.) und so kann man dann auch in späteren Versionen Grafiken anzeigen.
Das würde von der Datenhaltung auch Sinn machen, wenn man bedenkt, dass das Aufzeichnen einer neuen Route ja erstmal als Fahrt gewertet werden kann und der User dann das Ganze in eine Route überführt und diese benötigt ja die einzelnen Punkte.

Bei der Gesamtlänge/-zeit hatte ich überlegt, dass man jene zwar berechnen könnte, es aber eigentlich wenig Sinn macht, dies jedes Mal, wenn ein Nutzer sich Routen in der Nähe ansieht, neu zu berechnen.

**Comment by darenegade** [comment]
Guter Punkt mit den Streckenpunkten in der Fahrt. Können wir gerne so machen.

Bei der Länge gehe ich auch d'accord

**Comment by Plebo13** [comment]
Die Strecke lässt sich wirklich leicht anhand der Streckenpunkte berechnen. Ich hätte das einmalig im Konstruktor der Route machen lassen.

Die Route könnte man eventuell noch um ein Höhenprofil und die Fahrt um Höchstgeschwindigkeit erweitern.

**Comment by darenegade** [comment]
Okay hier die neue Version:
![datamodel](https://cloud.githubusercontent.com/assets/10849776/14060997/2201558c-f375-11e5-8a94-4d2a697eb21e.png)

**Comment by NeelzDev** [comment]
Gefällt mir sehr gut Rene.
Ist Fahrt und Messung nicht eine 1:1 zu Ordnung? Also in meinem Verständnis ist jede Aufzeichnung ja eine Fahrt und somit individuell, also nur eine Bestimmte Messung. Was bedeuten würde man kann, die beiden Entitäten zusammemfassen.

**Comment by darenegade** [comment]
Während der Fahrt werden zu gewissen Zeitpunkten, z.B. jede Sekunde, eine Messung gemacht. Die Gesamtheit aller Messungen vom Start bis zum Ziel ergibt dann die gesamte Fahrt.

**Comment by darenegade** [comment]
Eine regelmäßige Messung macht die Zeit in der Messung natürlich obsolet, aber hier kann es ja eventuell zu Abweichungen kommen, daher habe ich es mit rein genommen.

**Comment by NeelzDev** [comment]
Ah okay. So macht es Sinn. Aber bestünde dann nicht eine andere Zuordnung zwischen Messung und Streckenpunkt. Also einer Messung ist immer ein Streckenpunkt zugeordnet aber nicht umgekehrt?

**Comment by darenegade** [comment]
So ist es gedacht: Eine Messung hat immer einen Streckenpunkt, aber ein Streckenpunkt kann mehreren Messungen zugeordnet sein.

https://de.wikipedia.org/wiki/Kardinalität_(Datenbankmodellierung)#1:n_.28n:1.29

**Comment by NeelzDev** [comment]
Okay. Aber ist das denn wirklich realistisch, dass exakt der selbe Punkt bei zwei Messungen auftaucht?
Dachte da eher an 1 oder 0.

**Comment by darenegade** [comment]
Es gibt viele Situationen, wo ein Streckenpunkt mehrfach von unterschiedlichen Messungen erfasst werden kann:
- Man steht an der Ampel
- Jemand anderes fährt die gleiche Route
- Eine Route kreuzt eine andere
- ..

**Comment by NeelzDev** [comment]
Ja aber mein Bedenken bei all diesen Fällen ist, dass die Wahrscheinlichkeit, dass zwei Leute an der gleichen Stelle exakt die gleichen Koordinaten messen, doch sehr gering ist. GPS hat ja nur eine Genauigkeit von ungefähr 5m. Deswegen habe ich gedacht, dass, obwohl die Möglichkeit besteht, nahezu nie ein Punkt doppelt aufgezeichnet wird. Aber wir können, dass trotzdem gern so beibehalten, schadet ja auch nicht.

**Comment by darenegade** [comment]
Murphys Law 😅

**Comment by darenegade** [comment]
Datenmodell wurde im Backend umgesetzt:
https://github.com/darenegade/BikeBattleBackend/pull/4

**Comment by NeelzDev** [comment]
Das Zeit und Geschwindigkeit in den von Google gegeben Wegpunkten enthalten ist, brauchen wir den Datentyp Messung nicht oder? Also eine Fahrt hat auch einfach nur n Wegpunkte!?

**Comment by darenegade** [comment]
Zeit ist nicht drin. Lat, Long, Altitude und dies sind enthalten. 

Gesendet von meinem Toaster

**Comment by NeelzDev** [comment]
Ja der Timestamp wird durch die Location Klasse von Google gegeben.
Schreibe grad die Grundfunktionen für das Datenmodell und da gibt es die Funktion bereits, sodass wir die Entität Messung nicht brauchen (meiner Meinung nach :D )

**Comment by Plebo13** [comment]
Habe noch ne Frage zu deinen Modell-Klassen @HoldemJhon: Wenn ich einen neue route hinzufüge, dann übergebe ich ja im Konstruktor einen Owner, sollte dann nicht auch auf den Owner addRoute aufgerufen werden?

**Comment by NeelzDev** [comment]
Wäre eine Möglichkeit. Falls das Feld Owner erhalten bleibt. Rene hatte vorgeschlagen, dass es nicht nötig ist. Für den Moment kannst du ja einfach selbst addRoute aufrufen.

**Comment by darenegade** [comment]
Also im Backend speichere ich keine Bidirektionalen Beziehungen, da dies nicht nur umständlich sondern auch unnötig ist. Im Backend gibt es dann eine Methode findBy , wo man mit der ID von der Route den owner bekommt.  Daher müsst ihr es in der App auch nicht tun. Wenn ein Nutzer eine Route speichert, dann speichert er diese über seine User ID. Also auf dem Endpunkt /users/{id}/routes. Damit ist sie mit den owner verbunden. Wenn man die Route über den Endpunkt /routes/ bekommt, dann hat man die Route ID mit der man den owner auch bekommt. 
Für diese ganzen Fälle gibt es in der API, die ich gerade schreibe, entsprechende Methoden.

**Comment by Plebo13** [comment]
Alles klar

**Comment by NeelzDev** [comment]
Dann wird das Feld User bei Route und Track entfernt.
Ich kümmer mich drum.
