### ISSUE TITLE
Workflow der App erstellen

### ISSUE THREAD

**Issue by darenegade** [darenegade/BikeBattle#8]
Wir sollten über ein Workflow nachdenken und Konzepte hier posten.

Hier geht es um die Navigation in der App.

**Comment by NeelzDev** [comment]
https://guides.github.com/introduction/flow/

Ich würde Renes Vorschlag nehmen.

Für jedes Issue, das jemand bearbeitet, erstellt derjenige für sich einen neuen Branch und merged das ganze sobald das okay der anderen Mitglieder gegeben worden ist. Habe ich das richtig verstanden?

**Comment by darenegade** [comment]
Das Issue soll nicht den Workflow vom Projekt beschreiben, sondern den von der App. Also welche View zu welcher navigiert usw.

**Comment by darenegade** [comment]
Hab das jetzt etwas genauer oben Beschrieben, damit kein Missverständnis mehr auftritt

**Comment by darenegade** [comment]
Siehe https://github.com/darenegade/BikeBattle/issues/38
